### ISSUE TITLE
Path Finding in Image

### ISSUE THREAD

**Issue by harshpatel2212** [MSTC-DA-IICT/Hacktoberfest22-Python-2#3]
Given an Image, you are supposed to write an algorithm in python to find the shortest distance from source to destination(given as pixels) and highlight it.

General Guidelines:
1. Code should be neat clean, well-formatted, and commented.
2. If there is a need to change the file or folder structure you may do so, but maintain the integrity of the repository.

Good to go developers! 🚀

**Comment by Jam-Burger** [comment]
I would like to contribute on this issue

**Comment by harshpatel2212** [comment]
> I would like to contribute on this issue

@Jam-Burger, Sure You may proceed with the issue.

Happy Developing🚀

**Comment by naisargi1101** [comment]
I would like to contribute on this issue

**Comment by Jam-Burger** [comment]
which type of images should I use? Shall I use the images created on my own?

**Comment by harshpatel2212** [comment]
> I would like to contribute on this issue

Already one @Jam-Burger is assigned this issue. We will assign you, If the issue is not solved till 10th October.

**Comment by harshpatel2212** [comment]
> which type of images should I use? Shall I use the images created on my own?

You may use any image and then try to form a canvas, it would be than easier to mark points on it and draw path on it.

**Comment by Jam-Burger** [comment]
> > which type of images should I use? Shall I use the images created on my own?
> 
> You may use any image and then try to form a canvas, it would be than easier to mark points on it and draw path on it.

okay
